# Map from Python format to Moment format
mapping = {
    "%a": "ddd",
    "%A": "dddd",
    "%w": "e",
    "%d": "DD",
    "%b": "MMM",
    "%B": "MMMM",
    "%m": "MM",
    "%y": "YY",
    "%Y": "YYYY",
    "%H": "HH",
    "%I": "hh",
    "%p": "A",
    "%M": "mm",
    "%S": "ss",
    "%f": "SSSSSSSSS",
    "%z": "+-HHmm",
    "%Z": "ZZ",
    "%j": "DDDD",
    "%U": "ww",
    "%W": "ww",
    "%c": "LLL",
    "%x": "L",
    "%X": "LTS",
    "%%": "%",
    "%G": "GGGG",
    "%u": "E",
    "%V": "WW"
}
